version: "3.8"
services:
  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./server:/app
    command: npm run dev

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./client:/app
    command: npm run dev
